# 多智能体系统最优配置
# 基于参数实验和问题分析的优化配置
project_name: Multi-Agent Data Lake Discovery (Optimized)
version: 2.0-optimized
debug: false

# LLM配置 - 必须启用
llm:
  provider: gemini
  model_name: gemini-1.5-flash
  temperature: 0.0
  max_tokens: 1000
  timeout: 30
  max_retries: 5  # 增加重试次数
  retry_delay: 2
  batch_size: 10

# 向量搜索配置 - 优化阈值
vector_search:
  similarity_threshold: 0.35  # 降低阈值提高召回率
  top_k: 80  # 增加候选数量
  use_precomputed: true
  embedding_model: all-MiniLM-L6-v2
  index_type: hnsw
  hnsw_params:
    M: 16
    ef_construction: 200
    ef_search: 160

# 元数据过滤 - 放宽条件
metadata_filter:
  column_similarity_threshold: 0.35  # 降低阈值
  min_column_overlap: 2  # 至少2列重叠
  fuzzy_match: true
  use_type_matching: true
  use_name_similarity: true
  max_candidates: 150

# LLM匹配器 - 智能验证
llm_matcher:
  confidence_threshold: 0.55  # 平衡精度和召回
  batch_size: 10
  use_caching: true
  cache_ttl: 3600
  max_retries: 3
  timeout: 20
  enable_llm: true  # 必须启用

# 评分策略 - 优化权重
scoring:
  # 基于实验结果的最优权重
  weights:
    metadata: 0.25  # 结构匹配
    vector: 0.40    # 语义相似性（最重要）
    llm: 0.35       # 智能验证
  
  # 增强排序
  use_composite_score: true
  normalize_scores: true
  ranking_algorithm: weighted_sum
  
  # 特殊加分项
  boost_factors:
    exact_name_match: 1.5
    high_column_overlap: 1.3
    same_domain: 1.1
    llm_high_confidence: 1.2

# 多智能体系统配置
agents:
  # 优化器Agent
  optimizer:
    enable_cache: true
    cache_ttl: 3600
    parallel_workers: 8
    batch_size: 10
  
  # 规划器Agent
  planner:
    enable_cache: true
    cache_ttl: 3600
    strategy_preference: bottom-up  # JOIN任务优先bottom-up
  
  # 分析器Agent
  analyzer:
    enable_llm: true
    analysis_depth: detailed
    pattern_detection: true
  
  # 搜索器Agent
  searcher:
    parallel_search: true
    max_parallel: 5
    use_multi_layer: true
    layer_config:
      L1_metadata: true
      L2_vector: true
      L3_llm: true
  
  # 匹配器Agent
  matcher:
    enable_llm: true  # 必须启用LLM
    batch_size: 10
    parallel_matching: true
    confidence_boost: 1.1
    cache_results: true
  
  # 聚合器Agent
  aggregator:
    min_score: 0.3
    max_results: 20
    use_composite_ranking: true
    filter_self_match: true  # 过滤自匹配

# 性能优化
performance:
  enable_parallel: true
  max_workers: 3
  batch_processing: true
  cache_enabled: true
  cache_size: 1000
  memory_limit: 4096  # MB
  
  # 超时设置
  timeouts:
    agent_timeout: 60
    llm_timeout: 30
    search_timeout: 10

# 数据目录
data_dir: ./data
cache_dir: ./cache
log_dir: ./logs

# 日志配置
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/system.log
  rotate: true
  max_size: 10485760  # 10MB
  backup_count: 5

# 实验配置（用于优化）
experiment:
  enable_metrics: true
  track_performance: true
  save_intermediate: false
  benchmark_mode: false